version: '3.3'
services:
   mysql:
     image: mysql:5.7
     volumes:
       - ./data/mysql:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_ROOT_HOST: '%'
   phpmyadmin:
     depends_on:
       - mysql
     image: phpmyadmin
     restart: always
     environment:
       PMA_HOST: mysql
       PMA_USER: root
       PMA_PASSWORD: password
       PMA_ABSOLUTE_URI: /phpmyadmin/
   backend:
     depends_on:
       - mysql
     build: ./backend/
     volumes:
       - ./data/backend:/app/storage
     restart: always
     environment:
       DATABASE_HOST: mysql
   frontend:
     build: ./frontend/
     restart: always
     environment:
       DATABASE_HOST: mysql
   gateway:
     build: ./gateway/
     restart: always
     ports:
       - "80:80"
