logging:
  level:
    root: INFO
    org.quartz: WARN
    negrosa.backend: INFO
server:
  port: 8000
  error:
    include-stacktrace: always
spring:
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:tournament}?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD}
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: false #true
#    show-sql: true #false
    properties:
      hibernate:
        globally_quoted_identifiers: true
        enable_lazy_load_no_trans: true
references:
  storage:
    images:
      path: ${REFERENCES_STORAGE_IMAGES:storage/references/}
      extension: ${REFERENCES_STORAGE_IMAGES_EXTENSION:png}
    temporary:
      path: ${REFERENCES_STORAGE_TEMPORARY:storage/temporary/}
      prefix: ${REFERENCES_STORAGE_TEMPORARY_PREFIX:ref_}
  extension: ${REFERENCES_EXTENSION:dxf}
  